# Generated by Django 2.2 on 2020-05-27 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=10)),
                ('hours', models.IntegerField(editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Must be 10 characters', regex='^.{10}$')])),
                ('grade', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('hours', models.IntegerField()),
                ('category', models.CharField(choices=[('N/A', 'N/A'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='N/A', editable=False, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
